### ISSUE TITLE
Put Crowdbreaks under maintenance

### ISSUE THREAD

**Issue by yannis** [digitalepidemiologylab/crowdbreaks#99]
- [ ] Put Heroku on maintenance
- [ ] Put AWS service (EC2s, lambdas, …) on sleep mode

**Comment by yannis** [comment]
Waiting for @lauespinosa ok before putting the app in maintenance.

**Comment by yannis** [comment]
See https://digitalepidemiology.slack.com/archives/C37BXFDK2/p1683888541232439

> Laura Espinosa Montalban
> [12:49 PM](https://digitalepidemiology.slack.com/archives/C37BXFDK2/p1683888541232439)
> After discussing with Marcel, there are some aspects that are still relevant for the current article I am working on and potentially the remaining work of my PhD. It was taking me too much time trying to collect all this info and data. Marcel suggested to put in maintenance only the public website and leave the website for admins still running. 
[@marcel.salathe](https://digitalepidemiology.slack.com/team/U0EQ39MFY), please jump in if I understood it wrong

**Comment by yannis** [comment]
Hi @lauespinosa !
I hope you’re doing well. I’ve deployed some changes to crowdbreaks staging, removing public access (routing to a maintenance page instead) while keeping the admin access.
Could you check it out and see if you have everything you need there before I deploy it to production?
You can still sign in by directly following https://crowdbreaks-stg.herokuapp.com/en/users/sign_in
If you encounter a basic auth sign form the username/password to pass it is the crowbreaks vault on 1Password (crowdbreaks-stg.herokuapp.com). Let me know if you encounter any issues.
Thanks!

**Comment by lauespinosa** [comment]
Hi @yannis ,

Thank you, you can deploy to production, I can see everything I need
